# Generated by Django 4.2.4 on 2023-08-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sumka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='', max_length=201)),
                ('invented_country', models.CharField(default='', max_length=201)),
            ],
        ),
        migrations.CreateModel(
            name='university',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=190)),
                ('filiallari', models.PositiveIntegerField(default=1)),
                ('kantrakti', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
